Implement 03-lection1-01-button
js-tasks-ru/htmlcss-20211125_dan-ignatov pull request #3
Opened 2022-01-05 09:23 UTC by IgnatovDan

2022-01-05 09:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-05 10:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-05 10:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-05 10:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-06 18:09 UTC, GSemikozov requested changes

2022-01-06 18:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    all: unset;
здесь и.ниже вот эти сбросы стилей можно унести из компонента в normalize.css

2022-01-06 18:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    - there is no design for .button:focus (focus-visible/focus-within) - https://developer.mozilla.org/en-US/docs/Web/CSS/:focus
:hover = :active = :focus

2022-01-06 18:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    - there is no design for .button[disabled]:hover (?)
у disabled не может быть ховера

2022-01-06 18:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:focus,
вот эти штуки для дебага удалим

2022-01-06 18:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +        box-sizing: border-box;
лучше сразу указать на. .button

2022-01-06 18:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
disabled будет одинаковым для всех типов, поэтому можно объединить в один общий модификатор .button_disabled или просто :disabled { opacity: 0.5; pointer-events: none } (последнее свойство не будет давать пользователю взаимодействовать с disabled элементом)

2022-01-06 18:10 UTC, GSemikozov requested changes

2022-01-06 18:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
да, и цвет соответственно тогда менять тоже не надо, достаточно opacity

2022-01-06 18:57 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    - there is no design for .button:focus (focus-visible/focus-within) - https://developer.mozilla.org/en-US/docs/Web/CSS/:focus
ok, значит ТЗ хочет одинаковый внешний вид на эти расклады.
Скоро будет.
Это конечно проще, чем делать визуальную индикацию для "button уже отработал мой клик мышой или надо еще раз кликнуть?" или для "указатель мыши над одной button, фокус в другой button, выглядят они одинаково - кто сработает, когда я нажму Enter?"

2022-01-06 18:58 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    all: unset;
ОК, скоро будет.

2022-01-06 19:01 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    - there is no design for .button[disabled]:hover (?)
По моей логике тоже не должно быть ни ховера, ни фокуса, ни клавиатуры, ни default, ни form, ни тача... Но я не проверял (17! браузеров в caniuse) и поэтому добавил в список.

2022-01-06 19:02 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +.button:focus,
ok, скоро будет

2022-01-06 21:23 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    all: unset;
Я сейчас скопировал к себе https://yarnpkg.com/en/package/normalize.css и удалил свой 'unset' внутри компонента.
На 4К кнопка выглядит так же как с 'all: unset' (посмотрел на edge/chrome/ff/opera).
На HD edge/chrome/ff/opera все равно рисуют свою фокусную рамку вокруг моей кнопки (у меня два моника):
![image](https://user-images.githubusercontent.com/2094015/148446324-5b731af5-725e-4335-9f8a-a3ee9310ecae.png)

Т.е. работа этих браузеров на HD мониторах больше соответствует макету, если используется настройка 'all: unset' , чем с normalize.css (HD сейчас в лидерах, 4K очень мало: https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide).

Еще с normalize.css надо знать, что мой компонент требует normalize.css и его надо подключать в своем проекте (хотя он наверняка уже везде есть).

Можно еще вписать "all: unset" для тега \<button\> в свою копию normalize.
И тогда использовать мой компонент в других проектах (т.е. скопировать) станет еще немного сложнее: надо не забыть вырезать эту строчку из моего normalize и аккуратно вставить ее в свой normalize.
Еще надо точно знать не сломает ли этот 'all: unset' другие компоненты на тэге \<button\> в новом проекте (наверняка на \<button\> будут и другие компоненты).

Поэтому я засунул именно 'all:unset' именно в мой класс: знать не надо, точно скопируется, ни на кого не повлияет, отрисовка по макету.

Я выполнил все важные шаги для выбора варианта решения?
Мой вывод адекватный?
Оставляем 'all: unset' ?

2022-01-06 21:24 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    - there is no design for .button:focus (focus-visible/focus-within) - https://developer.mozilla.org/en-US/docs/Web/CSS/:focus
Готово.

2022-01-06 21:24 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +.button:focus,
Готово.

2022-01-06 21:24 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +        box-sizing: border-box;
Уже поставил на '.button'
Тут забыл удалить.

2022-01-06 21:26 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
- pointer-events: none - кмк евентов много и разработчики браузеров должны все отключить лучше меня: ["The disabled attribute is used to make the control non-interactive"](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#concept-fe-disabled). Одного 'disabled' должно хватать без моих дополнительных настроек и вроде бы и правда хватает (chrome/edge/ff/opera).

Я выполнил все важные шаги для выбора варианта решения?
Не связываемся с 'pointer-events: none'?

- и цвет соответственно тогда менять тоже не надо - по макету в Figma есть конкретный цвет "#ACB5BD". Если оставить только 'opacity: 0.5' + 'color: #495057' (тоже из макета), то я даже не знаю как считать итоговый цвет (#A4A8AB?). Поэтому я не стал сокращать и оставлять только исходный цвет + opacity. Сократить количество констант можно только "через дизайнера" (уже одобрил :) ).

Поменял на 'opacity: 0.5'.
Я выполнил все важные шаги для выбора варианта решения?

2022-01-07 10:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    all: unset;
хорошая работа проделана, так и надо проверять)
но - я имел в виду просто расширить normalize, это не набор правил который нельзя менять )

2022-01-07 10:11 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
если добавляем не модификатор, а атрибут disabled - тогда pointer-events не надо

в дизайне сделано именно так, что opacity будет достаточно)

2022-01-07 17:18 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    all: unset;
Да. Я понял, что normalize часто меняют и я могу в него влезать "по локоть" и менять что угодно (хз позволяет так MIT или нет, но вроде все так уже делают). Можно его поменять, а можно и оставить локальный "all:unset". Возможны оба варианта, у каждого свои +/-.

2022-01-09 19:50 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
https://www.w3.org/TR/selectors-3/#enableddisabled - это псевдо-класс, который добавляется браузером при блокировке взаимодействия пользователя с элементом.

Этот псевдо-класс выглядит как следствие от добавления атрибута [disabled] и я вроде бы могу настраивать мои стили как на появление атрибута, так и на появление псевдо-класса. Это должна быть одна и та же ситуация для браузера:

1. если есть атрибут, значит будет псевдо-класс (и взаимодействие пользователя с элементом заблокировано)
2. если нет псевдо-класса, значит и атрибута нет (и взаимодействие пользователя с элементом никто не блокировал)

2022-01-09 19:54 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
На других платформах я несколько раз видел что disabled (полное блокирование взаимодействия) путают с readonly (взаимодействие возможно, заблокировано только изменение значения). Для readonly действительно будет нужна другая обработка (например, какая-то блокировка событий/кнопок).
Но я настраиваю элемент button и в его сценариях все получается сделать на disabled.

2022-01-15 17:49 UTC, IgnatovDan commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
> в дизайне сделано именно так, что opacity будет достаточно)

Что-то у меня цвета не сошлись с Figma :(
С явным цветом rgbA с заданием в нем opacity:

![image](https://user-images.githubusercontent.com/2094015/149632262-36dd2cfc-7121-4172-92f0-6478cf25a817.png)

Без явного цвета с заданием только opacity на элементе:

![image](https://user-images.githubusercontent.com/2094015/149632285-79355428-d4ab-41b4-9637-d300c478cedf.png)

Не понятно где грабли :(

2022-01-16 09:56 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    .button_primary[disabled]
можем с изменением цвета

2022-01-16 09:56 UTC, GSemikozov approved these changes

2022-01-16 09:56 UTC, merged