Implement 03-lection1-02-accordion
js-tasks-ru/htmlcss-20211125_dan-ignatov pull request #5
Opened 2022-01-07 22:04 UTC by IgnatovDan

Preview:

![image](https://user-images.githubusercontent.com/2094015/148613312-66107951-09ef-44b6-a53d-069f145d06d1.png)

2022-01-07 22:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-07 22:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-07 22:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-08 09:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-09 06:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-09 07:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-09 20:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-09 20:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-12 19:44 UTC, GSemikozov requested changes

2022-01-12 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +        не заставлять прописывать классы БЭМ элементов, а сразу декларировать стили на тэги.
вот это и есть одна из наиболее часто встречаемых ошибок когда работаем с БЭМ - так нельзя :) советую перечитать статьи по БЭМ которые были даны в качестве материалов для обучения по ходу лекции, там очень подробно описаны основные ошибки при использовании БЭМ и ПОЧЕМУ на самом деле это ошибки

2022-01-12 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +        не заставлять прописывать классы БЭМ элементов, а сразу декларировать стили на тэги.
так что во всем ПР на поправить - теги переписать на классы и избегать вложенных селекторов

2022-01-12 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +        padding-top: 24px;
вместо четырех отдельных можно указать короткую запись - padding

2022-01-12 19:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +        margin-right: -16px;
а для чего отрицательный марджин?

2022-01-13 10:14 UTC, IgnatovDan commented on 03-lection1/02-accordion/accordion.css
> +        не заставлять прописывать классы БЭМ элементов, а сразу декларировать стили на тэги.
Да, я прошляпил: [Совмещение тега и класса в селекторе](https://ru.bem.info/methodology/css/#%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D0%B3%D0%B0-%D0%B8-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0-%D0%B2-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B5)

Именно в этом упражнении используются тэги ```<details><summary /><details>``` и мой компонент сразу основан на использовании поведения, которое предоставляет UA для этих тэгов: обработка переходов фокуса, визуализация фокуса, мышиные клики, кнопки клавиатуры, тач устройства, другие специальные устройства, раскрытие/схлопывание, работа в разных состояниях.
Все это уже есть и я не делаю это поведение в моем CSS коде, а компонент просто не будет работать на других тэгах или на другой структуре тэгов.

Но из-за разной специфичности селекторов с тэгами и без тэгов ["БЭМ не рекомендует совмещать теги и классы в селекторе"](https://ru.bem.info/methodology/css/#%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D0%B3%D0%B0-%D0%B8-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0-%D0%B2-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B5).

Лучше прописывать CSS классы даже в единственно возможном контексте применения правил в HTML разметке, когда эти классы явно можно полностью исключить из кода и использовать имена тэгов в селекторах. Даже если компонент завязан на конкретные тэги и точно не будет работать на других и логическая структура компонента неразрывно связана со структурой тэгов..

Поправил на классы.

2022-01-13 10:15 UTC, IgnatovDan commented on 03-lection1/02-accordion/accordion.css
> +        padding-top: 24px;
Да, можно укоротить запись.

Я знаю об этой возможности и сознательно не использую ее: сейчас я еще не запомнил все 4 коротких варианта записи значений для padding, и мне гораздо легче понимать каким будет каждый отступ из варианта полной записи, чем из любого из 4х вариантов сокращенной записи.

А быстрое понимание всего алгоритма для меня сейчас важнее, чем умение вставлять разные 'overloads'. Им точно можно заняться после курса.

Для "привыкшего" глаза это может выглядеть дико, [но я еще не привык и всего лишь подаю ключи](https://baneks.ru/452) ;-)

Уменьшение размера файла для меня сейчас тоже не важно. Кмк экономией на размере через overloads вообще не стоит озабочиваться.

2022-01-13 10:15 UTC, IgnatovDan commented on 03-lection1/02-accordion/accordion.css
> +        margin-right: -16px;
Справедливый вопрос: я не использовал возможности, что бы сделать очевидным зачем здесь margin и почему он именно такой.

Переделал и для очевидности этой связи я сейчас добавил переменную:
```--accordionPaddings: 24px calc(32px + var(--itemSummaryOpenCloseButtonWidth)) 24px 32px;```

На ней я сделал выравнивание правого края содержимого по левому краю картинки '\\/'
Выравнивание похоже на выравнивание в столбцах/ячейках css-grid, но он будет только через 2 занятия и я не пробовал его тут использовать.

Я использовал именно отрицательный margin, что бы сохранить возможность задания контента без декларации отдельного div:
```
        <details class="accordion__item">
            <summary class="accordion__itemSummary">
                Accordion item 2
            </summary>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
        </details>
```

Если отказаться от этой возможности и требовать div, то можно сделать новый БЭМ элемент, убрать -margin и сделать padding-right:

```
        <details class="accordion__item">
            <summary class="accordion__itemSummary">
                Accordion item 2
            </summary>
            <div class="accordion__itemContent">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            </div>
        </details>

.accordion__itemContent {
    padding-right: var(--itemSummaryOpenCloseButtonWidth);
}
```

2022-01-13 15:33 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +        margin-right: -16px;
второй вариант будет предпочтительнее. Вообще, отрицательные марджины лучше использовать толко при крайней необходимости и там где точно очевидно для его это делается)

2022-01-13 16:25 UTC, IgnatovDan commented on 03-lection1/02-accordion/accordion.css
> +        margin-right: -16px;
Еще он попроще.
Поправил.

2022-01-15 17:41 UTC, GSemikozov approved these changes

2022-01-15 17:41 UTC, merged